export { Search } from './extension'
export { findTextMatches, leafTextFromRenderText } from './search'
export type { FindTextMatchesOptions } from './search'
export { getSearchState, searchPluginKey } from './search-state'
export type * from './types'
