packages:
  - 'packages/*'
  - '!packages/markdown-mobile' # 暂不打包 Webview 编辑器
  - '!packages/markdown-mobile-tiptap' # 暂不打包 Webview 编辑器
  - '!packages/markdown-studio' # 暂不打包 Webview 编辑器
  - '!packages/vsc-markdown-studio' # 暂不打包 VSCode 插件
#  - 'blocknote/**'
  - 'tiptap-editor/**'